In [1]:
import qgauss as qg
import numpy as np

In [2]:
"""
We start by modelling the familiar case of dispersive readout of a qubit coupled to a single linear mode in the vacuum. 
In this case we know that the measurement-induced dephasing will be identical to the measurement rate.
"""
# Begin by defining the annihilation operator for the linear mode, and the spin-z operator for the qubit.
a = qg.tensor(qg.destroy(),qg.identity_fls(2))
sz = qg.tensor(qg.identity_cvs(),qg.sigmaz())

# Parameters
chi = 2.75; lw = 6; eps = 6

# Define the Hamiltonian and Lindbladian.
H1_disp = chi*sz*a.dag()*a + eps*a.dag() + np.conj(eps)*a
L1 = qg.lindbladian(H = H1_disp, c_ops = [np.sqrt(lw)*a])

# Calculate the measurement-induced backation.
np.real(qg.backaction_steadystate(L1, qubit="e,g")[2])

np.float64(11.909604841580634)

In [6]:
"""
We can now model the measurement rate, which is defined using input-output theory and the Heisenberg-Langevin equations (HLEs), see
Gardiner & Collett, Phys. Rev. A 31, 3761 (1985). Since these equations cannot be uniquely defined from the Lindbladian and state
of the input fields, we must construct them directly from the system-bath Hamiltonian.
"""
# Define the annihilation operators for the system and the coupled environment; these need not be defined separately in this case,
#  but are done so here for clarity.
a_sys = qg.destroy()
a_bath = qg.destroy()

# Next, we defined the state of the environment, which in this case we take to be the vacuum state.
input1_bath_state = qg.vacuum()

""" We now define the system-bath coupling, which in this case is a beam-splitter. The phase we have chosen conforms to the choice in
Gardiner and Collett, which gives the following HLE for a_sys:
d/dt a_sys = -np.sqrt(lw)*a_bath + coherent terms
Flipping the phase on the beam-splitter would yield d/dt a_sys = np.sqrt(lw)*a_bath, etc."""
H1_sysbath = 1j*np.sqrt(lw)*( (a_sys & a_bath.dag()) - (a_sys.dag() & a_bath))

# NOTE: Based on the current code, it is required that all system modes be placed first in the 
# tensor product, and the bath modes last.

""" Now, we can use these objects, along with the original dispersive Hamiltonian, to create an instance of the
class representing the Heisenberg-Langevin equations, called QGhle. We creating this object, it is currently
required that the number of continuous variable modes, along with the number of baths, be passed to the
class constructor.

This can then be passed to the solver, where we notice that the measurement rate is identitical to the initial dephasing 
rate. We specify that the measurement is distinguishing between the excited and ground states of the qubit. """
HLE1 = qg.QGhle(h_sys = H1_disp, h_sys_bath = H1_sysbath, input_bath = input1_bath_state, dims_cvs = 1, dims_bath = 1)
qg.measurement_rate(HLE1, pointers='e,g')[0]

np.float64(11.909604841580638)

In [7]:
""" When defining the QGhle class, we can bypass defining the system-bath Hamiltonian, and instead pass a matrix of
rates represnting the coupling of the input fields to the system. So, for a system with HLEs of the form
    dr/dt = A @ r - sqrt(k) @ r_in
this required matrix corresponds to sqrt(k). If both this matrix and a system-bath Hailtonian are passed, this matrix
will be ignored. """
sqrtk = np.diag([np.sqrt(lw),np.sqrt(lw)])
HLE1_alt = qg.QGhle(h_sys = H1_disp, input_coupling_mat = sqrtk, input_bath = input1_bath_state, dims_cvs = 1, dims_bath = 1)
HLE1_alt == HLE1

True

In [9]:
""" Notice that the measurement rate includes the measurement signal and measurement noise. Since we did not specify a measurement 
operator for the output fields, one was calculated which optimized for the largest signal. We could have also specified the 
measurement operator, and the frequency of the output field that we would like to measure.

Additionally, if we do not specify the pair of state to measured, the measurement rates of all possible pairs are calculated.
Note, of course, that if the pointer states are the same (diagonal entires) then the measurement rate is zero. """

qg.measurement_rate(HLE1)[0]

array([[ 0.        , 11.90960484],
       [11.90960484,  0.        ]])

In [12]:
"""
We now model some measurement inneficiency, where the system decays into a monitored "external" environment and an
unmonitored "internal" environment. This is handled by coupling the system mode to two environmental modes.
"""
# Define the system and bath operators. For convenience, we will use the simpler constructors so that we can just multiply later.
a_sys = qg.destroy(1,3)
a_ext = qg.destroy(2,3)
a_int = qg.destroy(3,3)

# Specifiy the bath state, which in this case is a low-occupancy thermal state
input2A_bath_state = qg.thermal([0.003,0.003])

# Of the total decay rate of the system mode, 95% is into the monitored channel, while 5% represents internal losses.
lw_ext = 0.95*lw; lw_int = 0.05*lw

# We now defined the system-bath Hamiltonian, choosing arbitrary phases.
H2_sysbath = (1j*np.sqrt(lw_ext)*(a_sys*a_ext.dag() - a_sys.dag()*a_ext)
             + np.sqrt(lw_int)*(a_sys*a_int.dag() + a_sys.dag()*a_int))

# Since only a_ext is monitored, we specify that the monitored/measured mode is mode "1" since it is the first in
# the tensor product of the bath modes: """
HLE2A = qg.QGhle(h_sys = H1_disp, h_sys_bath = H2_sysbath, input_bath = input2A_bath_state, dims_cvs = 1, dims_bath = 2)
qg.measurement_rate(HLE2A, meas_mode=1, pointers='e,g')[0]

np.float64(11.246644731114914)

In [13]:
# We notice that the measurement rate is lower than before due to inefficiencies in the monitoring and due to bath being in
# a thermal state. If we do not specify which bath mode(s) to measure, all are included, in which case the measurement rate 
# is the same as in the inital example if the input state is the vacuum:
input2B_bath_state = qg.vacuum(2)
HLE2B = qg.QGhle(h_sys = H1_disp, h_sys_bath = H2_sysbath, input_bath = input2B_bath_state, dims_cvs = 1, dims_bath = 2)
qg.measurement_rate(HLE2B, pointers='e,g')[0]

np.float64(11.909604841580638)

In [17]:
"""
Now for something a bit different, we have two system modes which are not coherently coupled to each other, but are coupled to the
same qubit as well as the same bath. Additionally, squeezing is included on one of the modes to demonstrate the scope of the module.
"""
# Define the system and bath operators
a_sys = qg.tensor(qg.destroy(1,3),qg.identity_fls(2))
b_sys = qg.tensor(qg.destroy(2,3),qg.identity_fls(2))
sz = qg.tensor(qg.identity_cvs(3),qg.sigmaz())
c_bath = qg.tensor(qg.destroy(3,3),qg.identity_fls(2))

# In this case we will not include a drive term in the system Hamiltonian, but will instead model the drive as a displaced bath state.
input3_bath_state = qg.displaced(6)

# System parameters
chi_a = 5; chi_b = 3
lw_a = 12; lw_b = 20
amp = 2*np.exp(-0.5j*np.pi)
sqz = 2*np.exp(0.5j*np.pi)

# Define the system Hamiltonian for both phases
H3A_disp = (chi_a*a_sys.dag()*a_sys*sz
            + chi_b*b_sys.dag()*b_sys*sz
            + (amp*a_sys.dag()**2 + np.conj(amp)*a_sys**2))
H3B_disp = ( chi_a*a_sys.dag()*a_sys*sz_sys
            + chi_b*b_sys.dag()*b_sys*sz_sys
            + (sqz*a_sys.dag()**2 + np.conj(sqz)*a_sys**2))

# And now the bath Hamiltonian.
H3_sysbath = (1j*np.sqrt(lw_a)*(a_sys*c_bath.dag() - a_sys.dag()*c_bath)
              + np.sqrt(lw_b)*(b_sys*c_bath.dag() + b_sys.dag()*c_bath))

HLE3A = qg.QGhle(h_sys = H3A_disp, h_sys_bath = H3_sysbath, input_bath = input3_bath_state, dims_cvs = 2, dims_bath = 1)
HLE3B = qg.QGhle(h_sys = H3B_disp, h_sys_bath = H3_sysbath, input_bath = input3_bath_state, dims_cvs = 2, dims_bath = 1)

In [18]:
# Note that due to the presence of the single-mode squeezing, that the noise component is amplified and so above vacuum...
qg.measurement_rate(HLE3A, pointers='e,g')

(np.float64(3.3439767779390377),
 np.float64(4.35538752362948),
 np.float64(1.3024574669187132))

In [19]:
# ...but, if we change the phase then the noise is squeezed and hence below vacuum
qg.measurement_rate(HLE3B, pointers='e,g')

(np.float64(5.620060493706709),
 np.float64(4.355387523629493),
 np.float64(0.7749716446124761))

In [2]:
"""
For multiple qubits, multiple measurement rates can be defined between each pair. Again, the pair of states to be distinguished can
be specified, or not, in which case all are calculated.
"""
# Operators
c_sys = qg.tensor(qg.destroy(1,2),qg.identity_fls([2,2]))
c_bath = qg.tensor(qg.destroy(2,2),qg.identity_fls([2,2]))
sz1 = qg.tensor(qg.identity_cvs(2),qg.sigmaz(),qg.identity_fls(2))
sz2 = qg.tensor(qg.identity_cvs(2),qg.identity_fls(2),qg.sigmaz())

# Environment is a displaced state
input4_bath_state = qg.displaced(5)

# Parameters
chi_c1 = 2.5; chi_c2 = 5; lw_c = 6; lw_z = 0.1

# We now define our system and system-bath operators. We can even include qubit-dependent dissipation
H4_disp = chi_c1*c_sys.dag()*c_sys*sz1 + chi_c2*c_sys.dag()*c_sys*sz2
H4_sysbath = (1j*np.sqrt(lw_c)*(c_sys*c_bath.dag() - c_sys.dag()*c_bath)
              + np.sqrt(lw_z)*(c_sys*c_bath.dag() + c_sys.dag()*c_bath)*sz1)
HLE4 = qg.QGhle(h_sys = H4_disp, h_sys_bath = H4_sysbath, input_bath = input4_bath_state, dims_cvs = 1, dims_bath = 1)

# Here, we will define a pair of trial measurement operators, the position and momentum quadratures
meas_oper_q = qg.position()
meas_oper_p = qg.momentum()

In [3]:
# We first check the measurement rate using the position quadrature operator...
qg.measurement_rate(HLE4, meas_oper = meas_oper_q)[0]

array([[0.        , 5.20355844, 5.20355844, 0.        ],
       [5.20355844, 0.        , 0.        , 5.20355844],
       [5.20355844, 0.        , 0.        , 5.20355844],
       [0.        , 5.20355844, 5.20355844, 0.        ]])

In [4]:
# ...and notice that, compared to the momentum operator, it fails to distinguish certain pairs of pointer states.
qg.measurement_rate(HLE4, meas_oper = meas_oper_p)[0]

array([[ 0.        , 17.60775112,  0.49926895, 12.1770948 ],
       [17.60775112,  0.        , 24.03694535,  0.49926895],
       [ 0.49926895, 24.03694535,  0.        , 17.60775112],
       [12.1770948 ,  0.49926895, 17.60775112,  0.        ]])

In [6]:
# Letting the function calculate the optimum measurement operator for each possible pair of pointer states, we can see that
# neither the position or momentum quadratures were optimal for every pair.
qg.measurement_rate(HLE4)[0]

array([[ 0.        , 22.81130956,  5.70282739, 12.1770948 ],
       [22.81130956,  0.        , 24.03694535,  5.70282739],
       [ 5.70282739, 24.03694535,  0.        , 22.81130956],
       [12.1770948 ,  5.70282739, 22.81130956,  0.        ]])